In [2]:
import numpy as np


In [3]:
#normal indexing
n=[6,7,8,9]
n[0:3]

[6, 7, 8]

In [4]:
#indexing using numpy
a=np.array([6,7,8,9])
a[0:2]

array([6, 7])

In [5]:
a[-1]

9

In [7]:
a1=np.array([[6,7,8],
             [1,2,3],
             [9,3,2]])
a1[1,2]          #print 1st row 2nd element


3

In [8]:
a1[0:2,2]   #print 2nd elements from 0th to 1th 

array([8, 3])

In [9]:
a1[-1]      #print last element

array([9, 3, 2])

In [11]:
a1[-1,0:2]   #print o to 1 element of last row

array([9, 3])

In [13]:
a1[:,1:3]    #print all 1st and 2nd column elements

array([[7, 8],
       [2, 3],
       [3, 2]])

In [14]:
a1

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [16]:
#to print all 
for i in a1:
    print(i)

[6 7 8]
[1 2 3]
[9 3 2]


In [17]:
#to print all elements seprately
for i in a1.flat:
    print(i)

6
7
8
1
2
3
9
3
2


In [19]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
#to vertically stack both array like a box
np.vstack((a,b))


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [22]:
#to horizontally stack both array like a box
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [24]:
#splitting array
a2=np.arange(30).reshape(2,15)
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
            '''horizontal split'''

In [26]:
np.hsplit(a2,3) #divide array into 3 array

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [28]:
var=np.hsplit(a2,3)


In [29]:
var[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [30]:
var[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [31]:
var[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [ ]:
            '''vertical split'''

In [32]:
np.vsplit(a2,2) #2ch row ahet tyamule 2 bhagatch split hou shakt vertically 


[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [33]:
var1=np.vsplit(a2,2)
var1[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [34]:
var1[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [35]:
#boolean arrays
a3=np.arange(12).reshape(4,3)
a3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
b1=a3>4   #returns true if element is > 4
b1

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
a3[b1]    #return value of elements if it is true

array([ 5,  6,  7,  8,  9, 10, 11])

In [39]:
a3[b1]=-1  #replace all elements which are grater than 4 by -1
a3

array([[ 0,  1,  2],
       [ 3,  4, -1],
       [-1, -1, -1],
       [-1, -1, -1]])