In [1]:
import numpy as np

In [4]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [7]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
for i in np.nditer(a,order="F"):    #fortan order i.e.columnwise
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [12]:
for i in np.nditer(a,order="C"):    #c order row wise
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [13]:
#to print array oppositly
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
for i in np.nditer(a,order="F",flags=["external_loop"]):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [15]:
#to print square of each element in array
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
for i in np.nditer(a,op_flags=['readwrite']):
    i[...]=i*i
    
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [17]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [18]:
for i in a:
    i=i*i
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [19]:
#iterate 2 arrays

In [20]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [21]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [23]:
for i,j in np.nditer([a,b]):
    print(i,j)
'''general broadcasting rule  => this operations is possible only when 2 arrays 
have same size or one of them having 1 row or column''' 

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
