In [ ]:
#numpy is beneficial over directly using list because numpy array takes less space and they are fast 

In [1]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
result=a1+a2
print(result)


[5 7 9]


In [ ]:
#dimensional arrays and ndim property

In [17]:
#1 dimensional array
a3=np.array([5,6,9])
a3.ndim


1

In [18]:
#2 dimensional array
a4=np.array([[1,2],[3,4],[5,6]])
a4.ndim

2

In [ ]:
#itemsize and dataype property

In [19]:
a5=np.array([[1,2],[3,4],[5,6]])
a5.dtype

dtype('int32')

In [20]:
a5.itemsize

4

In [21]:
#changing datatype
a6=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
a6.itemsize

8

In [22]:
a6

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
#shape ,size property

In [23]:
a6

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [24]:
a6.size   #total elements

6

In [25]:
a6.shape  #no.of rows and columns i.e 3 rows and 2 colums

(3, 2)

In [ ]:
#complex property

In [26]:
a6=np.array([[1,2],[3,4],[5,6]], dtype=complex)
a6

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [ ]:
#zeros and ones function

In [27]:
np.zeros((3,4))   #CREATING ARRAY OF 3 ROWS AND 4 COLUMNS WITH VALUE 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((3,4))     #CREATING ARRAY OF 3 ROWS AND 4 COLUMNS WITH VALUE 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#range() and arange()

In [39]:
l=range(1,3)
print(l[0])
print(l[1])



1
2


In [37]:
np.arange(1,3)

array([1, 2])

In [40]:
np.arange(1,8,2)

array([1, 3, 5, 7])

In [ ]:
#linspace()

In [43]:
np.linspace(1,8,2)

array([1., 8.])

In [44]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [45]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
#reshape()

In [46]:
a8=np.array([[1,2],[3,4],[5,6]])
a8

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
a8.shape

(3, 2)

In [49]:
a8.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a8.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
#ravel()  => use to convert into 1d array

In [55]:
a8.ravel()

array([1, 2, 3, 4, 5, 6])

In [56]:
a8

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#min() and max()

In [61]:
a8

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
a8.min()

1

In [58]:
a8.max()

6

In [60]:
a8.sum()

21

In [ ]:
#axis()

In [59]:
a8

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
a8.sum(axis=0)   #sum of columns 

array([ 9, 12])

In [63]:
a8.sum(axis=1)  #sum of rows

array([ 3,  7, 11])

In [64]:
#sqrt()

In [65]:
a8

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
np.sqrt(a8)  #gives sqrt of all array

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
#standard deviation or std()

In [67]:
a8

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
np.std(a8)

1.707825127659933

In [69]:
#operations in array

In [71]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [72]:
a

array([[1, 2],
       [3, 4]])

In [73]:
b

array([[5, 6],
       [7, 8]])

In [74]:
a+b

array([[ 6,  8],
       [10, 12]])

In [75]:
a-b

array([[-4, -4],
       [-4, -4]])

In [76]:
a*b

array([[ 5, 12],
       [21, 32]])

In [77]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
#matrixproduct i.e. dot()

In [79]:
a

array([[1, 2],
       [3, 4]])

In [80]:
b

array([[5, 6],
       [7, 8]])

In [78]:
a.dot(b)

array([[19, 22],
       [43, 50]])